"""add bark_id

Revision ID: 12cd1ac845ac
Revises: 490d7a4b4639
Create Date: 2026-03-16 18:44:33.982478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cd1ac845ac'
down_revision = '490d7a4b4639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bark_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bark_id')

    # ### end Alembic commands ###
