"""V3.1 - Full Schema with Memories

Revision ID: 490d7a4b4639
Revises: 317b2003bf14
Create Date: 2025-11-17 21:42:36.705935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490d7a4b4639'
down_revision = '317b2003bf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_item')
    # ### end Alembic commands ###
