"""add push_subscription to user

Revision ID: acf0745ab1c0
Revises: fed0ce8a2975
Create Date: 2026-04-28 19:33:38.723821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf0745ab1c0'
down_revision = 'fed0ce8a2975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['daily_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.Text(), nullable=True))
        batch_op.drop_column('bark_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bark_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('push_subscription')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('category')

    op.drop_table('question_like')
    # ### end Alembic commands ###
